#!/usr/bin/env python3
"""Run warmed standalone stock-versus-NEON CLI repetitions on Phone 2."""

from __future__ import annotations

import argparse
import json
import os
import statistics
import time
from dataclasses import asdict, dataclass
from pathlib import Path

from edgesplit_bench import finish_attempt, invalidate_run, log_run, start_attempt
from run_cli_baseline import build_command, run


PINNED_COMMIT = "e920c523e3b8a0163fe498af5bf90df35ff51d25"


class RepetitionError(RuntimeError):
    """A standalone benchmark run could not be recorded."""


@dataclass(frozen=True)
class Measurement:
    row_id: int
    config: str
    ttft_seconds: float
    decode_tokens_per_second: float


def positive_int(value: str) -> int:
    parsed = int(value)
    if parsed <= 0:
        raise argparse.ArgumentTypeError("must be greater than zero")
    return parsed


def metric_summary(values: list[float]) -> dict[str, float | int]:
    if not values:
        raise RepetitionError("cannot summarize zero measurements")
    return {
        "n": len(values),
        "mean": statistics.fmean(values),
        "median": statistics.median(values),
        "sample_stdev": statistics.stdev(values) if len(values) > 1 else 0.0,
    }


def summarize(measurements: list[Measurement]) -> dict[str, dict[str, float | int]]:
    return {
        "ttft_seconds": metric_summary([item.ttft_seconds for item in measurements]),
        "decode_tokens_per_second": metric_summary(
            [item.decode_tokens_per_second for item in measurements]
        ),
    }


def run_variant(args: argparse.Namespace, *, config: str, llama_cli: Path) -> Measurement:
    run_args = argparse.Namespace(
        llama_cli=llama_cli,
        model=args.model,
        prompt=args.prompt,
        output_tokens=args.output_tokens,
        threads=args.threads,
        threads_batch=None,
        gpu_layers=None,
        extra_arg=["--no-mmap", "--ignore-eos", "--seed", str(args.seed), "--temp", "0"],
    )
    command = build_command(run_args)
    command_text = " ".join(command)
    attempt_id = start_attempt(args.db, {
        "device": args.device,
        "config": config,
        "model": args.model_name,
        "quant": args.quant,
        "prompt_len": str(len(args.prompt.split())),
        "output_len": str(args.output_tokens),
        "llama_cpp_commit": args.llama_cpp_commit,
    }, command_text)
    environment = os.environ.copy()
    environment["LD_LIBRARY_PATH"] = str(llama_cli.parent) + (
        ":" + environment["LD_LIBRARY_PATH"] if environment.get("LD_LIBRARY_PATH") else ""
    )
    try:
        ttft, tps, prompt_tokens, _ = run(command, run_args, env=environment)
        row_id = log_run(args.db, {
            "device": args.device,
            "config": config,
            "model": args.model_name,
            "quant": args.quant,
            "prompt_len": str(prompt_tokens),
            "output_len": str(args.output_tokens),
            "ttft": f"{ttft:.6f}",
            "tokens_per_sec": f"{tps:.6f}",
            "llama_cpp_commit": args.llama_cpp_commit,
            "notes": (
                "standalone llama-cli; ttft=first generated byte after prompt echo; "
                "tps=llama.cpp timing; threads=%d; no-mmap; seed=%d; temp=0; "
                "neon_patch=0002-edgesplit-neon-q4k-q8k-vector-accumulator; binary=%s"
            ) % (args.threads, args.seed, llama_cli),
        })
    except BaseException as exc:
        finish_attempt(args.db, attempt_id, "failed", error=f"{type(exc).__name__}: {exc}")
        raise
    finish_attempt(args.db, attempt_id, "completed", benchmark_run_id=row_id)
    print(f"row_id={row_id} config={config} ttft={ttft:.3f}s decode_tps={tps:.3f}", flush=True)
    return Measurement(row_id, config, ttft, tps)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--db", type=Path, required=True)
    parser.add_argument("--stock-cli", type=Path, required=True)
    parser.add_argument("--optimized-cli", type=Path, required=True)
    parser.add_argument("--model", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--device", default="android-phone-2")
    parser.add_argument("--model-name", default="Qwen3-0.6B")
    parser.add_argument("--quant", default="Q4_K_M")
    parser.add_argument("--llama-cpp-commit", default=PINNED_COMMIT)
    parser.add_argument("--prompt", default="Explain why the sky is blue in one sentence.")
    parser.add_argument("--output-tokens", type=positive_int, default=64)
    parser.add_argument("--threads", type=positive_int, default=2)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--warmups", type=int, default=1)
    parser.add_argument("--runs", type=positive_int, default=5)
    parser.add_argument("--pause-seconds", type=float, default=0.25)
    args = parser.parse_args()
    if args.warmups < 0 or args.pause_seconds < 0:
        parser.error("warmups and pause-seconds must be non-negative")
    for name, binary in (("stock", args.stock_cli), ("optimized", args.optimized_cli)):
        if not binary.is_file() or not os.access(binary, os.X_OK):
            parser.error(f"{name} llama-cli is not executable: {binary}")
    if not args.model.is_file():
        parser.error(f"model is not a file: {args.model}")

    warmups: list[Measurement] = []
    stock: list[Measurement] = []
    optimized: list[Measurement] = []
    variants = (
        ("phone-neon-stock", args.stock_cli, stock),
        ("phone-neon-optimized", args.optimized_cli, optimized),
    )
    for _ in range(args.warmups):
        for config, binary, _ in variants:
            measurement = run_variant(args, config=config, llama_cli=binary)
            if not invalidate_run(args.db, measurement.row_id, "excluded warm-up repetition"):
                raise RepetitionError(f"could not invalidate warm-up row {measurement.row_id}")
            warmups.append(measurement)
            if args.pause_seconds:
                time.sleep(args.pause_seconds)
    for _ in range(args.runs):
        for config, binary, collected in variants:
            collected.append(run_variant(args, config=config, llama_cli=binary))
            if args.pause_seconds:
                time.sleep(args.pause_seconds)

    evidence = {
        "method": {
            "mode": "standalone llama-cli; servers stopped",
            "prompt": args.prompt,
            "output_tokens": args.output_tokens,
            "threads": args.threads,
            "seed": args.seed,
            "temperature": 0,
            "no_mmap": True,
            "warmups_excluded_per_config": args.warmups,
            "recorded_pairs": args.runs,
            "pair_order": ["phone-neon-stock", "phone-neon-optimized"],
            "statistics": "mean, median, and sample standard deviation",
            "optimized_patch": "0002-edgesplit-neon-q4k-q8k-vector-accumulator.patch",
            "stock_cli": str(args.stock_cli),
            "optimized_cli": str(args.optimized_cli),
        },
        "quant": args.quant,
        "excluded_warmup_rows": [asdict(item) for item in warmups],
        "recorded_rows": {
            "phone-neon-stock": [asdict(item) for item in stock],
            "phone-neon-optimized": [asdict(item) for item in optimized],
        },
        "summary": {
            "phone-neon-stock": summarize(stock),
            "phone-neon-optimized": summarize(optimized),
        },
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(evidence, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(evidence["summary"], sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
